banned_games = [
  "League of Legends",
  "Fortnite",
  "Osu",
  "Honkai",
  "Genshin",
  "Valorant",
]

[replies.quoi]
replies = [
  "https://tenor.com/view/feur-quoi-clip-gif-21195505",
  "https://tenor.com/view/feur-theobabac-quoi-gif-24294658",
  "https://tenor.com/view/feur-meme-gif-24407942",
]

[replies.moi]
replies = [
  "https://media.discordapp.net/attachments/565193871265628213/930557511466110996/-_Tu_veux_sortir_avec_moi_.gif",
]

[replies.oui]
replies = [
  "https://tenor.com/view/stiti-oui-ouistiti-feur-best-joke-gif-22012916",
]
